set(LLVM_ENABLE_PROJECTS "clang;clang-tools-extra;lld" CACHE STRING "")
set(LLVM_ENABLE_RUNTIMES "compiler-rt;libcxx;libcxxabi;libunwind" CACHE STRING "")
set(BUILD_SHARED_LIBS OFF CACHE STRING "")

set(CMAKE_INSTALL_PREFIX "/system" CACHE STRING "")

set(CLANG_DEFAULT_CXX_STDLIB libc++ CACHE STRING "")
set(CLANG_DEFAULT_LINKER lld CACHE STRING "")
set(CLANG_DEFAULT_OBJCOPY llvm-objcopy CACHE STRING "")
set(CLANG_DEFAULT_RTLIB compiler-rt CACHE STRING "")
set(CLANG_DEFAULT_UNWINDLIB libunwind CACHE STRING "")

set(RUNTIMES_@@TRIPLE@@_LLVM_ENABLE_RUNTIMES "compiler-rt;libunwind;libcxx;libcxxabi" CACHE STRING "")

set(BUILTINS_@@TRIPLE@@_CMAKE_SYSTEM_NAME Popcorn CACHE STRING "")
set(BUILTINS_@@TRIPLE@@_CMAKE_C_FLAGS "--target=@@TRIPLE@@ --sysroot=@@SYSROOT@@" CACHE STRING "")
set(BUILTINS_@@TRIPLE@@_CMAKE_CXX_FLAGS "--target=@@TRIPLE@@ --sysroot=@@SYSROOT@@" CACHE STRING "")
set(BUILTINS_@@TRIPLE@@_CMAKE_EXE_LINKER_FLAGS "--target=@@TRIPLE@@ --sysroot=@@SYSROOT@@" CACHE STRING "")
set(BUILTINS_@@TRIPLE@@_CMAKE_SHARED_LINKER_FLAGS "--target=@@TRIPLE@@ --sysroot=@@SYSROOT@@" CACHE STRING "")
set(BUILTINS_@@TRIPLE@@_CMAKE_MODULE_LINKER_FLAGS "--target=@@TRIPLE@@ --sysroot=@@SYSROOT@@" CACHE STRING "")
set(BUILTINS_@@TRIPLE@@_CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY CACHE STRING "")

set(RUNTIMES_@@TRIPLE@@_CMAKE_SYSTEM_NAME Popcorn CACHE STRING "")
set(RUNTIMES_@@TRIPLE@@_CMAKE_C_FLAGS "--target=@@TRIPLE@@ --sysroot=@@SYSROOT@@" CACHE STRING "")
set(RUNTIMES_@@TRIPLE@@_CMAKE_CXX_FLAGS "--target=@@TRIPLE@@ --sysroot=@@SYSROOT@@" CACHE STRING "")
set(RUNTIMES_@@TRIPLE@@_CMAKE_EXE_LINKER_FLAGS "--target=@@TRIPLE@@ --sysroot=@@SYSROOT@@" CACHE STRING "")
set(RUNTIMES_@@TRIPLE@@_CMAKE_SHARED_LINKER_FLAGS "--target=@@TRIPLE@@ --sysroot=@@SYSROOT@@" CACHE STRING "")
set(RUNTIMES_@@TRIPLE@@_CMAKE_MODULE_LINKER_FLAGS "--target=@@TRIPLE@@ --sysroot=@@SYSROOT@@" CACHE STRING "")
set(RUNTIMES_@@TRIPLE@@_CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY CACHE STRING "")

set(RUNTIMES_@@TRIPLE@@_LIBUNWIND_ENABLE_SHARED OFF CACHE BOOL "")
set(RUNTIMES_@@TRIPLE@@_LIBUNWIND_INSTALL_LIBRARY ON CACHE BOOL "")
set(RUNTIMES_@@TRIPLE@@_LIBUNWIND_USE_COMPILER_RT ON CACHE BOOL "")

set(RUNTIMES_@@TRIPLE@@_COMPILER_RT_BUILD_BUILTINS ON CACHE BOOL "")
set(RUNTIMES_@@TRIPLE@@_COMPILER_RT_BUILD_LIBFUZZER OFF CACHE BOOL "")
set(RUNTIMES_@@TRIPLE@@_COMPILER_RT_BUILD_MEMPROF OFF CACHE BOOL "")
set(RUNTIMES_@@TRIPLE@@_COMPILER_RT_BUILD_PROFILE OFF CACHE BOOL "")
set(RUNTIMES_@@TRIPLE@@_COMPILER_RT_BUILD_SANITIZERS OFF CACHE BOOL "")
set(RUNTIMES_@@TRIPLE@@_COMPILER_RT_BUILD_XRAY OFF CACHE BOOL "")

set(RUNTIMES_@@TRIPLE@@_LIBCXXABI_ENABLE_SHARED OFF CACHE BOOL "")
set(RUNTIMES_@@TRIPLE@@_LIBCXXABI_ENABLE_STATIC_UNWINDER ON CACHE BOOL "")
set(RUNTIMES_@@TRIPLE@@_LIBCXXABI_INSTALL_LIBRARY ON CACHE BOOL "")
set(RUNTIMES_@@TRIPLE@@_LIBCXXABI_USE_COMPILER_RT ON CACHE BOOL "")
set(RUNTIMES_@@TRIPLE@@_LIBCXXABI_USE_LLVM_UNWINDER ON CACHE BOOL "")
set(RUNTIMES_@@TRIPLE@@_LIBCXXABI_LINK_TESTS_WITH_SHARED_LIBCXXABI OFF CACHE BOOL "")

set(RUNTIMES_@@TRIPLE@@_LIBCXX_ENABLE_SHARED OFF CACHE BOOL "")
set(RUNTIMES_@@TRIPLE@@_LIBCXX_ENABLE_STATIC_ABI_LIBRARY ON CACHE BOOL "")
set(RUNTIMES_@@TRIPLE@@_LIBCXX_USE_COMPILER_RT ON CACHE BOOL "")
set(RUNTIMES_@@TRIPLE@@_LIBCXX_CXX_ABI "libcxxabi" CACHE STRING "")
set(RUNTIMES_@@TRIPLE@@_LIBCXX_LINK_TESTS_WITH_SHARED_LIBCXX OFF CACHE BOOL "")

set(RUNTIMES_@@TRIPLE@@_LIBCXX_ABI_VERSION 2 CACHE STRING "")
set(RUNTIMES_@@TRIPLE@@_LIBCXX_ENABLE_STATIC ON CACHE BOOL "")
set(RUNTIMES_@@TRIPLE@@_LIBCXX_SHARED_OUTPUT_NAME "c++-shared" CACHE STRING "")
set(RUNTIMES_@@TRIPLE@@_LIBCXX_LIBC "system" CACHE STRING "")

set(RUNTIMES_@@TRIPLE@@_LIBCXX_ENABLE_FILESYSTEM OFF CACHE BOOL "")
set(RUNTIMES_@@TRIPLE@@_LIBCXX_ENABLE_RANDOM_DEVICE OFF CACHE BOOL "")
set(RUNTIMES_@@TRIPLE@@_LIBCXX_ENABLE_LOCALIZATION OFF CACHE BOOL "")
set(RUNTIMES_@@TRIPLE@@_LIBCXX_ENABLE_UNICODE OFF CACHE BOOL "")
set(RUNTIMES_@@TRIPLE@@_LIBCXX_ENABLE_WIDE_CHARACTERS TRUE CACHE BOOL "")
set(RUNTIMES_@@TRIPLE@@_LIBCXX_ENABLE_EXCEPTIONS OFF CACHE BOOL "")
set(RUNTIMES_@@TRIPLE@@_LIBCXX_ENABLE_RTTI OFF CACHE BOOL "")
set(RUNTIMES_@@TRIPLE@@_LIBCXX_ENABLE_THREADS ON CACHE BOOL "")
set(RUNTIMES_@@TRIPLE@@_LIBCXX_ENABLE_MONOTONIC_CLOCK ON CACHE BOOL "")
set(RUNTIMES_@@TRIPLE@@_LIBCXX_USE_COMPILER_RT ON CACHE BOOL "")

set(RUNTIMES_@@TRIPLE@@_LIBCXXABI_USE_COMPILER_RT ON CACHE BOOL "")
set(RUNTIMES_@@TRIPLE@@_LIBCXXABI_ENABLE_THREADS TRUE CACHE BOOL "")

set(RUNTIMES_@@TRIPLE@@_COMPILER_RT_BUILD_CRT OFF CACHE BOOL "")
set(RUNTIMES_@@TRIPLE@@_COMPILER_RT_BUILD_CTX_PROFILE OFF CACHE BOOL "")
set(RUNTIMES_@@TRIPLE@@_COMPILER_RT_BUILD_GWP_ASAN OFF CACHE BOOL "")
set(RUNTIMES_@@TRIPLE@@_COMPILER_RT_BUILD_ORC OFF CACHE BOOL "")

set(BUILTINS_@@TRIPLE@@_COMPILER_RT_BUILD_CRT OFF CACHE BOOL "")

set(LLVM_BUILTIN_TARGETS "@@TRIPLE@@" CACHE STRING "")
set(LLVM_RUNTIME_TARGETS "@@TRIPLE@@" CACHE STRING "")

set(LLVM_TARGETS_TO_BUILD "Native;X86" CACHE STRING "")

set(CMAKE_BUILD_TYPE RelWithDebInfo CACHE STRING "")
set(CMAKE_C_FLAGS_RELWITHDEBINFO "-O3 -gline-tables-only -DNDEBUG" CACHE STRING "")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-O3 -gline-tables-only -DNDEBUG" CACHE STRING "")
set(LLVM_ENABLE_LTO OFF CACHE BOOL "")

# Setup vendor-specific settings.
set(PACKAGE_VENDOR Popcorn2 CACHE STRING "")

set(CMAKE_OSX_ARCHITECTURES x86_64 CACHE STRING "")

if(APPLE)
  set(CMAKE_OSX_SYSROOT "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk" CACHE STRING "")
  set(BUILTINS_CMAKE_ARGS "-DCMAKE_OSX_SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk;-DCMAKE_OSX_ARCHITECTURES=${CMAKE_OSX_ARCHITECTURES}" CACHE STRING "")
  set(RUNTIMES_CMAKE_ARGS "-DCMAKE_OSX_SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk;-DCMAKE_OSX_ARCHITECTURES=${CMAKE_OSX_ARCHITECTURES}" CACHE STRING "")
endif()

set(LLVM_INSTALL_TOOLCHAIN_ONLY ON CACHE BOOL "")
set(LLVM_TOOLCHAIN_TOOLS
  dsymutil
  llvm-cov
  llvm-dwarfdump
  llvm-profdata
  llvm-objdump
  llvm-nm
  llvm-size
  llvm-cxxfilt
  llvm-config
  llvm-ar
  llvm-ranlib
  CACHE STRING "")

set(LLVM_DISTRIBUTION_COMPONENTS
  clang
  LTO
  clang-format
  clang-resource-headers
  lld
  ${LLVM_TOOLCHAIN_TOOLS}
  CACHE STRING "")
