set(CMAKE_SYSTEM_NAME Popcorn)
set(CMAKE_SYSTEM_PROCESSOR x86)

set(CMAKE_SYSROOT @@SYSROOT@@)

set(CMAKE_C_COMPILER @@TOOLCHAIN@@/system/bin/clang)
set(CMAKE_CXX_COMPILER @@TOOLCHAIN@@/system/bin/clang++)

set(CMAKE_C_COMPILER_TARGET "@@TRIPLE@@")
set(CMAKE_CXX_COMPILER_TARGET "@@TRIPLE@@")

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
